name: Build and Pages Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: npm install --prefix examples/react-webpack
      - run: npm install --prefix examples/vue-webpack
      - run: npm run build
      - run: npm run build:examples
      - name: Prepare examples for deployment
        run: |
          sed -i '/dist/d' .gitignore || true
          sed -i '/\/build/d' examples/react-webpack/.gitignore || true
          sed -i '/\/dist/d' examples/vue-webpack/.gitignore || true
          rm -rf examples/superhero-utils || true
          cp -r dist examples/superhero-utils
      - uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/master'
        with:
          name: examples
          path: examples

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: examples
          path: examples
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: examples
