name: Build and Pages Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      - run: npm install
      - run: npm install --prefix examples/react-vite
      - run: npm install --prefix examples/vue-vite
      - run: npm run build
      - run: npm run build:examples
      - name: Prepare examples for deployment
        run: |
          mkdir gh-pages
          mv dist gh-pages/superhero-utils
          mv examples/*.html gh-pages/
          mkdir gh-pages/react-vite
          mv examples/react-vite/dist gh-pages/react-vite/dist
          mkdir gh-pages/vue-vite
          mv examples/vue-vite/dist gh-pages/vue-vite/dist
      - uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/master'
        with:
          name: gh-pages
          path: gh-pages

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: gh-pages
          path: gh-pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
